#!/bin/bash

# FFA Cup Web Application - Setup Script
# This script helps you set up the .env file and verify your configuration

echo "🚀 FFA Cup Web Application - Setup"
echo "=================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if .env already exists
if [ -f .env ]; then
  echo -e "${YELLOW}⚠${NC} .env file already exists"
  read -p "Do you want to overwrite it? (y/N): " overwrite
  if [[ ! $overwrite =~ ^[Yy]$ ]]; then
    echo "Keeping existing .env file"
    exit 0
  fi
fi

echo "This script will help you create the .env file with your Supabase credentials."
echo ""
echo "You can find these values in your Supabase Dashboard:"
echo "  → Go to: https://supabase.com/dashboard"
echo "  → Select your project"
echo "  → Navigate to: Settings → API"
echo ""

# Get Supabase URL
read -p "Enter your Supabase Project URL (e.g., https://xxxxx.supabase.co): " SUPABASE_URL

# Validate URL format
if [[ ! $SUPABASE_URL =~ ^https://.*\.supabase\.co$ ]]; then
  echo -e "${RED}✗${NC} Invalid URL format. Expected: https://xxxxx.supabase.co"
  exit 1
fi

# Get Anon Key
echo ""
read -p "Enter your Supabase anon/public key: " ANON_KEY

if [ -z "$ANON_KEY" ]; then
  echo -e "${RED}✗${NC} Anon key cannot be empty"
  exit 1
fi

# Create .env file
cat > .env << EOF
# Supabase Configuration
# Generated by setup.sh on $(date)

VITE_SUPABASE_URL=${SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=${ANON_KEY}

# Optional: Override Edge Functions base path (defaults to /server)
# VITE_EDGE_FUNCTIONS_BASE=/server
EOF

echo ""
echo -e "${GREEN}✓${NC} .env file created successfully!"
echo ""
echo "Next steps:"
echo "1. Set Edge Function secrets:"
echo "   supabase secrets set SUPABASE_SERVICE_ROLE_KEY=your-service-role-key"
echo ""
echo "2. Deploy Edge Functions:"
echo "   supabase functions deploy server"
echo ""
echo "3. Start the dev server:"
echo "   npm run dev"
echo ""
echo "See SETUP_GUIDE.md for detailed instructions."
